name: 'Verify Github Secrets'
description: 'This action will verify all secrets used in yaml files are defined as github secrets associated with the repository'
author: Chris Tallman & Chad Oftedahl
branding:
  icon: 'user'
  color: 'red'
inputs:
  secrets: 
    description: 'Secrets JSON from workflow'
    required: false
  secret_names:
    description: 'Secret name JSON'
    required: false
  exclusions:
    description: 'Secrets to skip verifying'
    required: false
runs:
  using: 'node12'
  main: 'dist/index.js'
