name: 'Verify Secrets'
description: 'This action will verify all secrets used in yaml files are defined as github secrets.'
author: Chris Tallman
branding:
  icon: 'user'
  color: 'red'
inputs:
  access-token:  # id of input
    description: 'Personal Access Token'
    required: true
  repo:
    description: 'Name of Repo to scan'
    required: true
  owner:
    description: 'Repo Owner if Organization'
    required: false
runs:
  using: "composite"
  steps:
    - run: |
          pip3 install -r $GITHUB_ACTION_PATH/requirements.txt
          python3 $GITHUB_ACTION_PATH/check.py
      env:
        TOKEN: ${{ inputs.access-token }}
        OWNER: ${{ inputs.owner }}
        REPO: ${{ inputs.repo }}
      shell: bash
      