name: 'Verify Secrets'
description: 'This action will verify all secrets used in yaml files are defined in github.'
inputs:
  access-token:  # id of input
    description: 'Personal Access Token'
    required: true
    default: ''
  repo:
    description: 'Name of Repo to scan'
    required: true
    default: ''
  owner:
    description: 'Repo Owner if Organization'
    required: false
runs:
  using: "composite"
  steps:
    - run: |
          touch token.txt
          echo $TOKEN > token.txt
          cat token.txt
          sh ${{ github.action_path }}/check.sh
      env:
        TOKEN: ${{ inputs.access-token }}
        # OWNER: ${{ inputs.owner }}
        REPO: ${{ inputs.repo }}
      shell: bash
      