name: Reusable workflow with secrets

on:
  workflow_call:
    
    secrets:
      dont-verify-me-1:
        required: false
      dont-verify-me-2:
        required: false

jobs:

  do_nothing:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        shell: bash

    steps:
      - run: echo "HI BOB"